version: '3.8'

services:
  qwesty:
    build: .
    container_name: qwesty
    volumes:
      - ./config.toml:/app/config.toml:ro
      - quest-data:/data
    restart: unless-stopped
    networks:
      - qwesty-network

volumes:
  quest-data:

networks:
  quest-network:
    driver: bridge

